services:
  - type: web
    name: productivity-tips-api
    env: node
    plan: free
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/lexpierce/strapiconf2022-workshop-strapi
    branch: main
    buildCommand: bun install && bun build
    startCommand: bun start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: ~20.12.2
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: APP_KEYS
        generateValue: true

  - type: web
    name: productivity-tips-web
    env: node
    plan: free
    # Update the following line with your Remix GitHub repo
    repo: https://github.com/lexpierce/strapiconf2022-workshop-remix
    branch: step-5
    buildCommand: bun install && bun build
    startCommand: bun start
    envVars:
      - key: STRAPI_URL_BASE
        fromService:
          type: web
          name: productivity-tips-api
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: strapi
    plan: free # This database will expire 90 days after creation
